### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by andris155** [Kakifrucht/WorldGuardFix#12]
```
[17:33:19] [Server thread/ERROR]: Could not pass event AreaEffectCloudApplyEvent to WorldGuardFix v1.6.2
org.bukkit.event.EventException
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.9.2.jar:git-Paper-727]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callAreaEffectCloudApplyEvent(CraftEventFactory.java:1024) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.EntityAreaEffectCloud.m(EntityAreaEffectCloud.java:275) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1728) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1703) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1528) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:636) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:885) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: effect type cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:45) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:65) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:78) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:90) ~[patched_1.9.2.jar:git-Paper-727]
	at de.halfminer.worldguardfix.Listeners.disableCloudEffect(Listeners.java:124) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.9.2.jar:git-Paper-727]
	... 15 more
```

**Comment by Kakifrucht** [comment]
Can't reproduce, since it is most likely a plugin of yours causing this, I have tried to fix the stacktrace.
Please confirm if it worked or not. Update on SpigotMC.

**Comment by Kakifrucht** [comment]
I consider this fixed, please correct me if not.
